name: Build data from Excel

name: Build data from Excel

on:
  push:
    branches:
      - main
    paths:
      - "Template_Proyectos_Dashboard.xlsx"
  workflow_dispatch: {}  # Permite lanzarlo manualmente desde Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install pandas openpyxl

      - name: Convertir Excel a JSON
        run: |
          python scripts/convert_excel_to_json.py

      - name: Actualizar cache-bust.txt
        run: echo "$(date +'%Y-%m-%d_%H-%M-%S')" > cache-bust.txt

      - name: Commit y push automáticos
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git status
          # Fuerza la inclusión aunque estén en .gitignore
          git add -f data.json cache-bust.txt
          git commit -m "auto: actualizar datos desde Excel" || echo "Sin cambios que commitear"
          git push

