name: Enviar alertas de deadlines

on:
  schedule:
    - cron: "0 12 * * 1-5"   # L-V 12:00 UTC (09:00 Chile aprox)
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install xlsx nodemailer

      - name: Run alerts
        env:
          SMTP_SERVER:   ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:     ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          ALERT_TO:      ${{ secrets.ALERT_TO }}   # opcional, para pruebas
        run: node scripts/alertas.js
