name: Enviar alertas de deadlines

on:
  schedule:
    # Lunes a Viernes 12:00 UTC (≈ 09:00 Chile con DST)
    - cron: "0 12 * * 1-5"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias (según package.json)
        run: |
          npm ci || npm i

      # ⬇️ Descomenta si conviertes Excel->JSON en el pipeline
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'
      # - name: Convertir Excel a JSON
      #   run: python scripts/convert_excel_to_json.py

      - name: Enviar alertas
        env:
          SMTP_SERVER:   ${{ secrets.SMTP_SERVER }}   # p.ej. smtp.gmail.com
          SMTP_PORT:     ${{ secrets.SMTP_PORT }}     # p.ej. 587
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MAIL_FROM:     ${{ secrets.MAIL_FROM }}     # obligatorio en muchos SMTP
          ALERT_TO:      ${{ secrets.ALERT_TO }}      # "a@b.com,c@d.com"
        run: |
          npm run alertas
